services:
  mysqldb:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - $DB_PORT:3306
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysqldb
    container_name: pma
    restart: always
    env_file: .env
    ports:
      - $PHPMYADMIN_PORT:80
    environment:
      - PMA_ARBITRARY=0

volumes:
  db:
