import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1767694222430 implements MigrationInterface {
    name = 'Migration1767694222430'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`product_variant_discounts\` (\`id\` int NOT NULL AUTO_INCREMENT, \`discountPercent\` decimal(5,2) NOT NULL, \`startDate\` timestamp NULL, \`endDate\` timestamp NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`product_variant_id\` int NULL, UNIQUE INDEX \`REL_a90e9e74f2f7158aa5bd8efec3\` (\`product_variant_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`sources\` CHANGE \`code\` \`code\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`product_storages\` DROP FOREIGN KEY \`FK_fdd2aafdd48fdc8bf8f8182d5de\``);
        await queryRunner.query(`ALTER TABLE \`product_storages\` CHANGE \`salesPointId\` \`salesPointId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`sales_points\` DROP COLUMN \`location\``);
        await queryRunner.query(`ALTER TABLE \`sales_points\` ADD \`location\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`sizes\` CHANGE \`deleted_at\` \`deleted_at\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`colors\` CHANGE \`deleted_at\` \`deleted_at\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`product_variant_measurements\` DROP FOREIGN KEY \`FK_bbb3b5757c05b67ca4377ef2385\``);
        await queryRunner.query(`ALTER TABLE \`product_variant_measurements\` CHANGE \`width\` \`width\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`product_variant_measurements\` CHANGE \`height\` \`height\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`product_variant_measurements\` CHANGE \`length\` \`length\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`product_variant_measurements\` CHANGE \`weight\` \`weight\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`product_variant_measurements\` CHANGE \`productVariantId\` \`productVariantId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`countries\` CHANGE \`flag\` \`flag\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`countries\` DROP COLUMN \`position\``);
        await queryRunner.query(`ALTER TABLE \`countries\` ADD \`position\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`cities\` DROP FOREIGN KEY \`FK_b5f9bef6e3609b50aac3e103ab3\``);
        await queryRunner.query(`ALTER TABLE \`cities\` DROP COLUMN \`position\``);
        await queryRunner.query(`ALTER TABLE \`cities\` ADD \`position\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`cities\` CHANGE \`countryId\` \`countryId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`delivery_types\` DROP FOREIGN KEY \`FK_ad385b72bf9a0d219f31891e1e3\``);
        await queryRunner.query(`ALTER TABLE \`delivery_types\` CHANGE \`description\` \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`delivery_types\` CHANGE \`cityId\` \`cityId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_c137e0afcc291b9135d3e0c3d4e\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_a1338be7dad63518a5a81adb08d\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_d99d0a81a68b46cdeb5ad1f32fa\``);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`phone\` \`phone\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`clientName\` \`clientName\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`comment\` \`comment\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`paymentMethodId\` \`paymentMethodId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`sourceId\` \`sourceId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`deliveryTypeId\` \`deliveryTypeId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`order_status_histories\` DROP FOREIGN KEY \`FK_dc2882bd01a30f6478b7ff1ca4f\``);
        await queryRunner.query(`ALTER TABLE \`order_status_histories\` DROP FOREIGN KEY \`FK_b0ca41322c3030160fe8ea26aa3\``);
        await queryRunner.query(`ALTER TABLE \`order_status_histories\` DROP FOREIGN KEY \`FK_b670aa41b6798e486dacf0df619\``);
        await queryRunner.query(`ALTER TABLE \`order_status_histories\` CHANGE \`changedBy\` \`changedBy\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`order_status_histories\` CHANGE \`orderId\` \`orderId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`order_status_histories\` CHANGE \`fromStatusId\` \`fromStatusId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`order_status_histories\` CHANGE \`toStatusId\` \`toStatusId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`product_categories\` DROP FOREIGN KEY \`FK_f0104fa49fb1974840ee758db8f\``);
        await queryRunner.query(`ALTER TABLE \`product_categories\` CHANGE \`parent_category_id\` \`parent_category_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`product_categories\` CHANGE \`is_hide\` \`is_hide\` tinyint NULL`);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_f1d359a55923bb45b057fbdab0d\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`orderId\` \`orderId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`order_status_notifications\` DROP FOREIGN KEY \`FK_311349201d16855fb6603194a93\``);
        await queryRunner.query(`ALTER TABLE \`order_status_notifications\` CHANGE \`statusId\` \`statusId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`order_addresses\` DROP FOREIGN KEY \`FK_1a2657b551b95bf3c2be3d1170c\``);
        await queryRunner.query(`ALTER TABLE \`order_addresses\` DROP FOREIGN KEY \`FK_ed333921b5c9a3a5b80c814dd18\``);
        await queryRunner.query(`ALTER TABLE \`order_addresses\` DROP FOREIGN KEY \`FK_5a7a31d083eb92037372eacf509\``);
        await queryRunner.query(`ALTER TABLE \`order_addresses\` CHANGE \`comment\` \`comment\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`order_addresses\` CHANGE \`entrance\` \`entrance\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`order_addresses\` CHANGE \`floor\` \`floor\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`order_addresses\` CHANGE \`intercom\` \`intercom\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`order_addresses\` DROP COLUMN \`position\``);
        await queryRunner.query(`ALTER TABLE \`order_addresses\` ADD \`position\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`order_addresses\` CHANGE \`orderId\` \`orderId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`order_addresses\` CHANGE \`countryId\` \`countryId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`order_addresses\` CHANGE \`cityId\` \`cityId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`product_storages\` ADD CONSTRAINT \`FK_fdd2aafdd48fdc8bf8f8182d5de\` FOREIGN KEY (\`salesPointId\`) REFERENCES \`sales_points\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_variant_discounts\` ADD CONSTRAINT \`FK_a90e9e74f2f7158aa5bd8efec3a\` FOREIGN KEY (\`product_variant_id\`) REFERENCES \`product_variants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_variant_measurements\` ADD CONSTRAINT \`FK_bbb3b5757c05b67ca4377ef2385\` FOREIGN KEY (\`productVariantId\`) REFERENCES \`product_variants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cities\` ADD CONSTRAINT \`FK_b5f9bef6e3609b50aac3e103ab3\` FOREIGN KEY (\`countryId\`) REFERENCES \`countries\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`delivery_types\` ADD CONSTRAINT \`FK_ad385b72bf9a0d219f31891e1e3\` FOREIGN KEY (\`cityId\`) REFERENCES \`cities\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_c137e0afcc291b9135d3e0c3d4e\` FOREIGN KEY (\`paymentMethodId\`) REFERENCES \`payment_methods\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_a1338be7dad63518a5a81adb08d\` FOREIGN KEY (\`sourceId\`) REFERENCES \`sources\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_d99d0a81a68b46cdeb5ad1f32fa\` FOREIGN KEY (\`deliveryTypeId\`) REFERENCES \`delivery_types\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_status_histories\` ADD CONSTRAINT \`FK_dc2882bd01a30f6478b7ff1ca4f\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_status_histories\` ADD CONSTRAINT \`FK_b0ca41322c3030160fe8ea26aa3\` FOREIGN KEY (\`fromStatusId\`) REFERENCES \`order_statuses\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_status_histories\` ADD CONSTRAINT \`FK_b670aa41b6798e486dacf0df619\` FOREIGN KEY (\`toStatusId\`) REFERENCES \`order_statuses\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_categories\` ADD CONSTRAINT \`FK_f0104fa49fb1974840ee758db8f\` FOREIGN KEY (\`parent_category_id\`) REFERENCES \`product_categories\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_f1d359a55923bb45b057fbdab0d\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_status_notifications\` ADD CONSTRAINT \`FK_311349201d16855fb6603194a93\` FOREIGN KEY (\`statusId\`) REFERENCES \`order_statuses\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_addresses\` ADD CONSTRAINT \`FK_1a2657b551b95bf3c2be3d1170c\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_addresses\` ADD CONSTRAINT \`FK_ed333921b5c9a3a5b80c814dd18\` FOREIGN KEY (\`countryId\`) REFERENCES \`countries\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_addresses\` ADD CONSTRAINT \`FK_5a7a31d083eb92037372eacf509\` FOREIGN KEY (\`cityId\`) REFERENCES \`cities\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`order_addresses\` DROP FOREIGN KEY \`FK_5a7a31d083eb92037372eacf509\``);
        await queryRunner.query(`ALTER TABLE \`order_addresses\` DROP FOREIGN KEY \`FK_ed333921b5c9a3a5b80c814dd18\``);
        await queryRunner.query(`ALTER TABLE \`order_addresses\` DROP FOREIGN KEY \`FK_1a2657b551b95bf3c2be3d1170c\``);
        await queryRunner.query(`ALTER TABLE \`order_status_notifications\` DROP FOREIGN KEY \`FK_311349201d16855fb6603194a93\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_f1d359a55923bb45b057fbdab0d\``);
        await queryRunner.query(`ALTER TABLE \`product_categories\` DROP FOREIGN KEY \`FK_f0104fa49fb1974840ee758db8f\``);
        await queryRunner.query(`ALTER TABLE \`order_status_histories\` DROP FOREIGN KEY \`FK_b670aa41b6798e486dacf0df619\``);
        await queryRunner.query(`ALTER TABLE \`order_status_histories\` DROP FOREIGN KEY \`FK_b0ca41322c3030160fe8ea26aa3\``);
        await queryRunner.query(`ALTER TABLE \`order_status_histories\` DROP FOREIGN KEY \`FK_dc2882bd01a30f6478b7ff1ca4f\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_d99d0a81a68b46cdeb5ad1f32fa\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_a1338be7dad63518a5a81adb08d\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_c137e0afcc291b9135d3e0c3d4e\``);
        await queryRunner.query(`ALTER TABLE \`delivery_types\` DROP FOREIGN KEY \`FK_ad385b72bf9a0d219f31891e1e3\``);
        await queryRunner.query(`ALTER TABLE \`cities\` DROP FOREIGN KEY \`FK_b5f9bef6e3609b50aac3e103ab3\``);
        await queryRunner.query(`ALTER TABLE \`product_variant_measurements\` DROP FOREIGN KEY \`FK_bbb3b5757c05b67ca4377ef2385\``);
        await queryRunner.query(`ALTER TABLE \`product_variant_discounts\` DROP FOREIGN KEY \`FK_a90e9e74f2f7158aa5bd8efec3a\``);
        await queryRunner.query(`ALTER TABLE \`product_storages\` DROP FOREIGN KEY \`FK_fdd2aafdd48fdc8bf8f8182d5de\``);
        await queryRunner.query(`ALTER TABLE \`order_addresses\` CHANGE \`cityId\` \`cityId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_addresses\` CHANGE \`countryId\` \`countryId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_addresses\` CHANGE \`orderId\` \`orderId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_addresses\` DROP COLUMN \`position\``);
        await queryRunner.query(`ALTER TABLE \`order_addresses\` ADD \`position\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_addresses\` CHANGE \`intercom\` \`intercom\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_addresses\` CHANGE \`floor\` \`floor\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_addresses\` CHANGE \`entrance\` \`entrance\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_addresses\` CHANGE \`comment\` \`comment\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_addresses\` ADD CONSTRAINT \`FK_5a7a31d083eb92037372eacf509\` FOREIGN KEY (\`cityId\`) REFERENCES \`cities\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_addresses\` ADD CONSTRAINT \`FK_ed333921b5c9a3a5b80c814dd18\` FOREIGN KEY (\`countryId\`) REFERENCES \`countries\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_addresses\` ADD CONSTRAINT \`FK_1a2657b551b95bf3c2be3d1170c\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_status_notifications\` CHANGE \`statusId\` \`statusId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_status_notifications\` ADD CONSTRAINT \`FK_311349201d16855fb6603194a93\` FOREIGN KEY (\`statusId\`) REFERENCES \`order_statuses\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`orderId\` \`orderId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_f1d359a55923bb45b057fbdab0d\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_categories\` CHANGE \`is_hide\` \`is_hide\` tinyint NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product_categories\` CHANGE \`parent_category_id\` \`parent_category_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product_categories\` ADD CONSTRAINT \`FK_f0104fa49fb1974840ee758db8f\` FOREIGN KEY (\`parent_category_id\`) REFERENCES \`product_categories\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_status_histories\` CHANGE \`toStatusId\` \`toStatusId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_status_histories\` CHANGE \`fromStatusId\` \`fromStatusId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_status_histories\` CHANGE \`orderId\` \`orderId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_status_histories\` CHANGE \`changedBy\` \`changedBy\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_status_histories\` ADD CONSTRAINT \`FK_b670aa41b6798e486dacf0df619\` FOREIGN KEY (\`toStatusId\`) REFERENCES \`order_statuses\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_status_histories\` ADD CONSTRAINT \`FK_b0ca41322c3030160fe8ea26aa3\` FOREIGN KEY (\`fromStatusId\`) REFERENCES \`order_statuses\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_status_histories\` ADD CONSTRAINT \`FK_dc2882bd01a30f6478b7ff1ca4f\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`deliveryTypeId\` \`deliveryTypeId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`sourceId\` \`sourceId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`paymentMethodId\` \`paymentMethodId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`comment\` \`comment\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`clientName\` \`clientName\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`phone\` \`phone\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_d99d0a81a68b46cdeb5ad1f32fa\` FOREIGN KEY (\`deliveryTypeId\`) REFERENCES \`delivery_types\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_a1338be7dad63518a5a81adb08d\` FOREIGN KEY (\`sourceId\`) REFERENCES \`sources\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_c137e0afcc291b9135d3e0c3d4e\` FOREIGN KEY (\`paymentMethodId\`) REFERENCES \`payment_methods\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`delivery_types\` CHANGE \`cityId\` \`cityId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`delivery_types\` CHANGE \`description\` \`description\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`delivery_types\` ADD CONSTRAINT \`FK_ad385b72bf9a0d219f31891e1e3\` FOREIGN KEY (\`cityId\`) REFERENCES \`cities\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cities\` CHANGE \`countryId\` \`countryId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cities\` DROP COLUMN \`position\``);
        await queryRunner.query(`ALTER TABLE \`cities\` ADD \`position\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cities\` ADD CONSTRAINT \`FK_b5f9bef6e3609b50aac3e103ab3\` FOREIGN KEY (\`countryId\`) REFERENCES \`countries\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`countries\` DROP COLUMN \`position\``);
        await queryRunner.query(`ALTER TABLE \`countries\` ADD \`position\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`countries\` CHANGE \`flag\` \`flag\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product_variant_measurements\` CHANGE \`productVariantId\` \`productVariantId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product_variant_measurements\` CHANGE \`weight\` \`weight\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product_variant_measurements\` CHANGE \`length\` \`length\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product_variant_measurements\` CHANGE \`height\` \`height\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product_variant_measurements\` CHANGE \`width\` \`width\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product_variant_measurements\` ADD CONSTRAINT \`FK_bbb3b5757c05b67ca4377ef2385\` FOREIGN KEY (\`productVariantId\`) REFERENCES \`product_variants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`colors\` CHANGE \`deleted_at\` \`deleted_at\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`sizes\` CHANGE \`deleted_at\` \`deleted_at\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`sales_points\` DROP COLUMN \`location\``);
        await queryRunner.query(`ALTER TABLE \`sales_points\` ADD \`location\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product_storages\` CHANGE \`salesPointId\` \`salesPointId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product_storages\` ADD CONSTRAINT \`FK_fdd2aafdd48fdc8bf8f8182d5de\` FOREIGN KEY (\`salesPointId\`) REFERENCES \`sales_points\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sources\` CHANGE \`code\` \`code\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`DROP INDEX \`REL_a90e9e74f2f7158aa5bd8efec3\` ON \`product_variant_discounts\``);
        await queryRunner.query(`DROP TABLE \`product_variant_discounts\``);
    }

}
